### ISSUE TITLE
Remplacer les "w" par des espaces (" ")

### ISSUE THREAD

**Issue by GauthierPLM** [GuiThink/opc_projet3#1]
https://github.com/GuiThink/opc_projet3/blob/605a5bc15ba2ff2336c1ff3a38029429c97f9333/v2/level_1#L1-L15

Utiliser des espaces serait plus clair, et ne devrait rien changer à ton code (sauf le caractère utilisé pour représenter une case vite).

**Comment by GuiThink** [comment]
remplacé les murs par "#" et les espaces par  " "
